- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
- repo: https://github.com/prettier/prettier
  rev: v1.15.0
  hooks:
    - id: prettier
- repo: https://github.com/ansible/ansible-lint
  rev: v4.2.0rc1
  hooks:
    - id: ansible-lint
