---
- hosts: all
  gather_facts: no
  vars:
    db_username: matomo
    ansible_python_interpreter: "/usr/bin/python3"
  vars_files:
    - /opt/ansible/vars.yml
  tasks:
  - name: Apply motomo role
    include_role:
      name: matomo