---
- name: Restart Apache
  become: yes
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: Restart MySQL
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: yes